FROM node:18-alpine AS build

# Instala Bun
RUN apk add --no-cache curl && \
    curl -fsSL https://bun.sh/install | sh && \
    ln -s /root/.bun/bin/bun /usr/local/bin/bun

WORKDIR /app

COPY package.json ./
RUN bun install

COPY . .

RUN bun run build

# Etapa 2: Servir los archivos estáticos con nginx
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]