version: '3.9'

services:

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gestorplus-php
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - gestorplus-network
    depends_on:
      - db
      - redis
    environment:
      - TZ=America/Bogota
      - MAIL_HOST=smtp-relay.brevo.com
      - MAIL_PORT=587
      - MAIL_USERNAME=scrimsdiscord2@gmail.com
      - MAIL_PASSWORD=JLANaUHRTcVs3b0t
      - MAIL_FROM=no-reply@gestorplus.com
      - MAIL_FROM_NAME=Gestorplus
    command: ["sh", "-c", "until nc -z gestorplus-db 3306; do sleep 1; done; php-fpm"]

  nginx:
    image: nginx:latest
    container_name: gestorplus-nginx
    volumes:
      - ./backend:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - gestorplus-network
    environment:
      - TZ=America/Bogota

  db:
    image: mariadb:latest
    container_name: gestorplus-db
    environment:
      MYSQL_ROOT_PASSWORD: "gestorplustfu"
      MYSQL_DATABASE: "gestorplus"
      TZ: America/Bogota
    volumes:
      - ./bd/gestorplus2.sql:/docker-entrypoint-initdb.d/gestorplus2.sql
    ports:
      - "3306:3306"
    networks:
      - gestorplus-network

  redis:
    image: redis:alpine
    container_name: gestorplus-redis
    ports:
      - "6379:6379"
    networks:
      - gestorplus-network
    environment:
      - TZ=America/Bogota

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gestorplus-frontend-dev
    command: sh -c "npm start"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - gestorplus-network
    depends_on:
      - php
    environment:
      - TZ=America/Bogota
    profiles:
      - dev

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: gestorplus-frontend-prod
    ports:
      - "80:80"
    networks:
      - gestorplus-network
    profiles:
      - prod

networks:
  gestorplus-network:
    driver: bridge
