version: '3.8'

services:
  php:
    image: php:8.4.2-fpm
    container_name: gerstorplus-php
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: gerstorplus-nginx
    volumes:
      - ./backend:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"