-- MySQL Script generated by MySQL Workbench
-- Fri Oct 18 14:15:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestorplus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestorplus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestorplus` DEFAULT CHARACTER SET utf8 ;
USE `gestorplus` ;

-- -----------------------------------------------------
-- Table `gestorplus`.`hojadevida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`hojadevida` (
  `idHojadevida` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `ciudadNacimiento` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `telefonoFijo` VARCHAR(45) NULL DEFAULT NULL,
  `estadohojadevida` BIT NULL,
  PRIMARY KEY (`idHojadevida`),
  UNIQUE INDEX `idHojadevida_UNIQUE` (`idHojadevida` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`rol` (
  `idrol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(45) NOT NULL,
  `estadoRol` BIT(1) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`usuario` (
  `num_doc` INT(11) NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tipodDoc` VARCHAR(5) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `estado` BIT(1) NOT NULL,
  `hojadevida_idHojadevida` INT(11) NOT NULL,
  `rol_idrol` INT(11) NOT NULL,
  PRIMARY KEY (`num_doc`, `hojadevida_idHojadevida`, `rol_idrol`),
  UNIQUE INDEX `num_doc_UNIQUE` (`num_doc` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_usuario_hojadevida1_idx` (`hojadevida_idHojadevida` ASC) ,
  INDEX `fk_usuario_rol1_idx` (`rol_idrol` ASC) ,
  UNIQUE INDEX `hojadevida_idHojadevida_UNIQUE` (`hojadevida_idHojadevida` ASC) ,
  CONSTRAINT `fk_usuario_hojadevida1`
    FOREIGN KEY (`hojadevida_idHojadevida`)
    REFERENCES `gestorplus`.`hojadevida` (`idHojadevida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `gestorplus`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`ausencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`ausencia` (
  `idausencia` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `tipoAusencia` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `justificada` TINYINT(4) NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `usuario_num_doc` INT(11) NOT NULL,
  PRIMARY KEY (`idausencia`, `usuario_num_doc`),
  INDEX `fk_ausencia_usuario1_idx` (`usuario_num_doc` ASC) ,
  CONSTRAINT `fk_ausencia_usuario1`
    FOREIGN KEY (`usuario_num_doc`)
    REFERENCES `gestorplus`.`usuario` (`num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`notificacion` (
  `idnotificacion` INT(11) NOT NULL,
  `descripcionNotificacion` TEXT NOT NULL,
  `estadoNotificacion` BIT(1) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idnotificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`ausencia_has_notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`ausencia_has_notificacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ausencia_idausencia` INT(11) NULL DEFAULT NULL,
  `notificacion_idnotificacion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ausencias_idausencias` (`ausencia_idausencia` ASC) ,
  INDEX `notificaciones_idnotificacion` (`notificacion_idnotificacion` ASC) ,
  CONSTRAINT `ausencias_has_notificaciones_ibfk_1`
    FOREIGN KEY (`ausencia_idausencia`)
    REFERENCES `gestorplus`.`ausencia` (`idausencia`)
    ON DELETE CASCADE,
  CONSTRAINT `ausencias_has_notificaciones_ibfk_2`
    FOREIGN KEY (`notificacion_idnotificacion`)
    REFERENCES `gestorplus`.`notificacion` (`idnotificacion`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`cargo` (
  `idcargo` INT(11) NOT NULL,
  `nombreCargo` VARCHAR(45) NOT NULL,
  `estadoCargo` BIT(1) NOT NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`convocatoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`convocatoria` (
  `idconvocatoria` INT(11) NOT NULL,
  `nombreConvocatoria` VARCHAR(80) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `requisitos` TEXT NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `cantidadConvocatoria` INT(11) NULL,
  `cargo_idcargo` INT(11) NOT NULL,
  PRIMARY KEY (`idconvocatoria`, `cargo_idcargo`),
  INDEX `fk_convocatoria_cargo1_idx` (`cargo_idcargo` ASC) ,
  CONSTRAINT `fk_convocatoria_cargo1`
    FOREIGN KEY (`cargo_idcargo`)
    REFERENCES `gestorplus`.`cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`postulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`postulacion` (
  `idpostulaciones` INT(11) NOT NULL AUTO_INCREMENT,
  `estadoPostulacion` BIT(1) NOT NULL,
  `convocatoria_idconvocatoria` INT(11) NOT NULL,
  `usuario_num_doc` INT(11) NOT NULL,
  PRIMARY KEY (`idpostulaciones`, `convocatoria_idconvocatoria`, `usuario_num_doc`),
  INDEX `fk_postulacion_convocatoria1_idx` (`convocatoria_idconvocatoria` ASC) ,
  INDEX `fk_postulacion_usuario1_idx` (`usuario_num_doc` ASC) ,
  CONSTRAINT `fk_postulacion_convocatoria1`
    FOREIGN KEY (`convocatoria_idconvocatoria`)
    REFERENCES `gestorplus`.`convocatoria` (`idconvocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postulacion_usuario1`
    FOREIGN KEY (`usuario_num_doc`)
    REFERENCES `gestorplus`.`usuario` (`num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`entrevista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`entrevista` (
  `identrevista` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `lugarMedio` VARCHAR(45) NOT NULL,
  `postulacion_idpostulaciones` INT(11) NOT NULL,
  PRIMARY KEY (`identrevista`, `postulacion_idpostulaciones`),
  INDEX `fk_cita_postulacion1_idx` (`postulacion_idpostulaciones` ASC) ,
  CONSTRAINT `fk_cita_postulacion1`
    FOREIGN KEY (`postulacion_idpostulaciones`)
    REFERENCES `gestorplus`.`postulacion` (`idpostulaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`evaluacionesSg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`evaluacionesSg` (
  `idevaluacion` INT NOT NULL,
  `estado_salud` VARCHAR(45) NULL,
  `evaluacionRiesgos` VARCHAR(45) NULL,
  `recomendaciones` VARCHAR(45) NULL,
  `aptitudLaboral` VARCHAR(45) NULL,
  `comentarios` VARCHAR(45) NULL,
  `entrevista_identrevista` INT(11) NOT NULL,
  `entrevista_postulacion_idpostulaciones` INT(11) NOT NULL,
  PRIMARY KEY (`idevaluacion`, `entrevista_identrevista`, `entrevista_postulacion_idpostulaciones`),
  INDEX `fk_evaluacionesSg_entrevista1_idx` (`entrevista_identrevista` ASC, `entrevista_postulacion_idpostulaciones` ASC) ,
  CONSTRAINT `fk_evaluacionesSg_entrevista1`
    FOREIGN KEY (`entrevista_identrevista` , `entrevista_postulacion_idpostulaciones`)
    REFERENCES `gestorplus`.`entrevista` (`identrevista` , `postulacion_idpostulaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorplus`.`vinculacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`vinculacion` (
  `idvinculacion` INT(11) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `tipoContrato` VARCHAR(80) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `estado` BIT(1) NOT NULL,
  `fechaFirma` DATE NOT NULL,
  `documentoContrato` TINYINT(1) NULL DEFAULT NULL,
  `evaluacionesSg_idevaluacion` INT NOT NULL,
  `usuario_num_doc` INT(11) NOT NULL,
  PRIMARY KEY (`idvinculacion`, `evaluacionesSg_idevaluacion`, `usuario_num_doc`),
  INDEX `fk_vinculacion_evaluacionesSg1_idx` (`evaluacionesSg_idevaluacion` ASC) ,
  INDEX `fk_vinculacion_usuario1_idx` (`usuario_num_doc` ASC) ,
  CONSTRAINT `fk_vinculacion_evaluacionesSg1`
    FOREIGN KEY (`evaluacionesSg_idevaluacion`)
    REFERENCES `gestorplus`.`evaluacionesSg` (`idevaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vinculacion_usuario1`
    FOREIGN KEY (`usuario_num_doc`)
    REFERENCES `gestorplus`.`usuario` (`num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`horaextra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`horaextra` (
  `idHoraextra` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `horasExtra` TIME NOT NULL,
  `usuario_num_doc` INT(11) NOT NULL,
  PRIMARY KEY (`idHoraextra`, `usuario_num_doc`),
  INDEX `fk_horasextra_usuarios1_idx` (`usuario_num_doc` ASC) ,
  CONSTRAINT `fk_horasextra_usuarios1`
    FOREIGN KEY (`usuario_num_doc`)
    REFERENCES `gestorplus`.`usuario` (`num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`jornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`jornada` (
  `idJornada` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `horaEntrada` TIME NOT NULL,
  `horaSalida` TIME NOT NULL,
  `usuario_num_doc` INT(11) NOT NULL,
  PRIMARY KEY (`idJornada`, `usuario_num_doc`),
  INDEX `fk_jornada_usuarios1_idx` (`usuario_num_doc` ASC) ,
  CONSTRAINT `fk_jornada_usuarios1`
    FOREIGN KEY (`usuario_num_doc`)
    REFERENCES `gestorplus`.`usuario` (`num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`pazysalvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`pazysalvo` (
  `idpazysalvo` INT(11) NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(150) NOT NULL,
  `fechaEmision` DATE NOT NULL,
  `estado` BIT(1) NOT NULL,
  `documentoPazysalvo` TINYINT(1) NULL DEFAULT NULL,
  `vinculacion_idvinculacion` INT(11) NOT NULL,
  PRIMARY KEY (`idpazysalvo`, `vinculacion_idvinculacion`),
  INDEX `fk_pazysalvo_vinculacion1_idx` (`vinculacion_idvinculacion` ASC) ,
  CONSTRAINT `fk_pazysalvo_vinculacion1`
    FOREIGN KEY (`vinculacion_idvinculacion`)
    REFERENCES `gestorplus`.`vinculacion` (`idvinculacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`quejareclamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`quejareclamo` (
  `idquejaReclamo` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaRedactado` DATE NOT NULL,
  `tipoQuejaReclamo` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `usuario_num_doc` INT(11) NOT NULL,
  PRIMARY KEY (`idquejaReclamo`, `usuario_num_doc`),
  INDEX `fk_quejareclamo_usuario1_idx` (`usuario_num_doc` ASC) ,
  CONSTRAINT `fk_quejareclamo_usuario1`
    FOREIGN KEY (`usuario_num_doc`)
    REFERENCES `gestorplus`.`usuario` (`num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`vacacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`vacacion` (
  `idvacacion` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `aprovadoPor` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `usuario_num_doc` INT(11) NOT NULL,
  PRIMARY KEY (`idvacacion`, `usuario_num_doc`),
  INDEX `fk_vacacion_usuario1_idx` (`usuario_num_doc` ASC) ,
  CONSTRAINT `fk_vacacion_usuario1`
    FOREIGN KEY (`usuario_num_doc`)
    REFERENCES `gestorplus`.`usuario` (`num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorplus`.`certificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`certificado` (
  `idCertificado` INT NOT NULL,
  `certificadoLaboral` TINYINT(1) NOT NULL,
  `certificadoARL` TINYINT(1) NOT NULL,
  `vinculacion_idvinculacion` INT(11) NOT NULL,
  PRIMARY KEY (`idCertificado`, `vinculacion_idvinculacion`),
  INDEX `fk_certificado_vinculacion1_idx` (`vinculacion_idvinculacion` ASC) ,
  CONSTRAINT `fk_certificado_vinculacion1`
    FOREIGN KEY (`vinculacion_idvinculacion`)
    REFERENCES `gestorplus`.`vinculacion` (`idvinculacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorplus`.`estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`estudio` (
  `idestudio` VARCHAR(45) NOT NULL,
  `nivelEstudio` VARCHAR(45) NULL,
  `areaEstudio` VARCHAR(45) NULL,
  `estadoEstudio` VARCHAR(45) NULL,
  `fechaInicioEstudio` DATE NULL,
  `fechaFinEstudio` DATE NULL,
  `tituloEstudio` VARCHAR(45) NULL,
  `institucionEstudio` VARCHAR(45) NULL,
  `ubicacionEstudio` VARCHAR(45) NULL,
  `hojadevida_idHojadevida` INT(11) NOT NULL,
  PRIMARY KEY (`idestudio`, `hojadevida_idHojadevida`),
  INDEX `fk_estudios_hojadevida1_idx` (`hojadevida_idHojadevida` ASC) ,
  CONSTRAINT `fk_estudios_hojadevida1`
    FOREIGN KEY (`hojadevida_idHojadevida`)
    REFERENCES `gestorplus`.`hojadevida` (`idHojadevida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorplus`.`experienciaLaboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`experienciaLaboral` (
  `idexperienciaLaboral` VARCHAR(45) NOT NULL,
  `profesion` VARCHAR(45) NULL,
  `descripcionPerfil` VARCHAR(45) NULL,
  `fechaInicioExp` DATE NULL,
  `fechaFinExp` DATE NULL,
  `hojadevida_idHojadevida` INT(11) NOT NULL,
  PRIMARY KEY (`idexperienciaLaboral`, `hojadevida_idHojadevida`),
  INDEX `fk_experienciaLaboral_hojadevida1_idx` (`hojadevida_idHojadevida` ASC) ,
  CONSTRAINT `fk_experienciaLaboral_hojadevida1`
    FOREIGN KEY (`hojadevida_idHojadevida`)
    REFERENCES `gestorplus`.`hojadevida` (`idHojadevida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorplus`.`postulacion_has_notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`postulacion_has_notificacion` (
  `notificacion_idnotificacion` INT(11) NOT NULL,
  `postulacion_idpostulaciones` INT(11) NOT NULL,
  INDEX `fk_postulacion_has_notificacion_notificacion1_idx` (`notificacion_idnotificacion` ASC) ,
  INDEX `fk_postulacion_has_notificacion_postulacion1_idx` (`postulacion_idpostulaciones` ASC) ,
  CONSTRAINT `fk_postulacion_has_notificacion_notificacion1`
    FOREIGN KEY (`notificacion_idnotificacion`)
    REFERENCES `gestorplus`.`notificacion` (`idnotificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postulacion_has_notificacion_postulacion1`
    FOREIGN KEY (`postulacion_idpostulaciones`)
    REFERENCES `gestorplus`.`postulacion` (`idpostulaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestorplus`.`jornada_has_notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorplus`.`jornada_has_notificacion` (
  `notificacion_idnotificacion` INT(11) NOT NULL,
  `jornada_idJornada` INT(11) NOT NULL,
  INDEX `fk_jornada_has_notificacion_notificacion1_idx` (`notificacion_idnotificacion` ASC) ,
  INDEX `fk_jornada_has_notificacion_jornada1_idx` (`jornada_idJornada` ASC) ,
  CONSTRAINT `fk_jornada_has_notificacion_notificacion1`
    FOREIGN KEY (`notificacion_idnotificacion`)
    REFERENCES `gestorplus`.`notificacion` (`idnotificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jornada_has_notificacion_jornada1`
    FOREIGN KEY (`jornada_idJornada`)
    REFERENCES `gestorplus`.`jornada` (`idJornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
